name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

on:
  push:
    branches: [ "ci/cd", "master" ]
  pull_request:
    branches: [ "ci/cd", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew build #assemble

      - name: Save and Push Build
        run: |
          #mkdir -p build/
          ls -R ${{ env.main_project_module }}/build/outputs/apk/release/
          #mv -b ${{matrix.project}}/.pio/build/*/firmware.* ${{matrix.project}}/build_output/
          #ls -Rlh /build_output/
          #git config user.name github-actions
          #git config user.email github-actions@github.com
          #if git diff --exit-code; then
           #  git add build_output/
           #  git commit -am "GH Action Files added $(date +"%d-%m-%y_%T")"
           #  git push 
          #fi
